# Generated by Django 3.2.19 on 2023-06-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('accomodation_id', models.AutoField(primary_key=True, serialize=False)),
                ('accomodation_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('price_per_night', models.FloatField()),
                ('accomodation_type', models.IntegerField()),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
    ]
