# Generated by Django 3.2.19 on 2023-06-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='availability',
            new_name='availibility',
        ),
    ]
