# Generated by Django 3.2.19 on 2023-06-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0002_rename_availability_accommodation_availibility'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accommodation',
            new_name='Accomodation',
        ),
    ]
