# Generated by Django 3.2.19 on 2023-06-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0003_rename_accommodation_accomodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='accomodation_type',
            field=models.CharField(max_length=50),
        ),
    ]
