# Generated by Django 3.2.19 on 2023-06-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0005_accomodation_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
