# Generated by Django 3.2.19 on 2023-06-06 17:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_testimonials_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
