# Generated by Django 3.2.19 on 2023-06-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_testimonials_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'ordering': ['created_date']},
        ),
        migrations.RenameField(
            model_name='testimonials',
            old_name='date_created',
            new_name='created_date',
        ),
    ]
