# Generated by Django 3.2.19 on 2023-06-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0006_alter_accomodation_price_per_night'),
        ('testimonials', '0004_auto_20230613_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='accomodation_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accomodation', to='accomodation.accomodation'),
        ),
    ]
