# Generated by Django 3.2.19 on 2023-06-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0005_testimonials_accomodation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'ordering': ['-created_date']},
        ),
    ]
