# Generated by Django 3.2.19 on 2023-06-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0006_alter_testimonials_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
