# Generated by Django 3.2.19 on 2023-06-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookings_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='user_id',
            new_name='user',
        ),
    ]
