# Generated by Django 3.2.19 on 2023-06-20 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0005_accomodation_featured_image'),
        ('bookings', '0003_rename_user_id_bookings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='accomodation_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='accomodation.accomodation'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='num_guests',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='price_per_night',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='accomodation.accomodation'),
        ),
    ]
