# Generated by Django 3.2.19 on 2023-06-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20230620_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='price_per_night',
        ),
    ]
